package com.poc.solarvillage;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NewOrder implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Order Id")
	private java.lang.String orderId;
	@org.kie.api.definition.type.Label(value = "Customer Type")
	private java.lang.String customerType;

	public NewOrder() {
	}

	public java.lang.String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(java.lang.String orderId) {
		this.orderId = orderId;
	}

	public java.lang.String getCustomerType() {
		return this.customerType;
	}

	public void setCustomerType(java.lang.String customerType) {
		this.customerType = customerType;
	}

	public NewOrder(java.lang.String orderId, java.lang.String customerType) {
		this.orderId = orderId;
		this.customerType = customerType;
	}

}